components:
  schemas:
    Facet:
      description: |-
        ```text
                      Back
                  +--------+     z ^   y
                 /        /|       |  /
                /        / |       | /
               /  Top   /  |       |/
              /        /   |       *--------> x
             +--------+ Ri-|
             |        | ght+
        Left | Front  |   /
             |        |  /
             |        | /
             |        |/
             +--------+
               Bottom
        ```
      enum:
      - front
      - back
      - left
      - right
      - top
      - bottom
      title: Facet
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Re-cube
  version: 0.1.0
openapi: 3.0.2
paths:
  /hposter/{x1}.{y1}.{z1}/{x2}.{y2}.{z2}/{facet}:
    get:
      operationId: hposter_hposter__x1___y1___z1___x2___y2___z2___facet__get
      parameters:
      - in: path
        name: x1
        required: true
        schema:
          title: X1
          type: integer
      - in: path
        name: y1
        required: true
        schema:
          title: Y1
          type: integer
      - in: path
        name: z1
        required: true
        schema:
          title: Z1
          type: integer
      - in: path
        name: x2
        required: true
        schema:
          title: X2
          type: integer
      - in: path
        name: y2
        required: true
        schema:
          title: Y2
          type: integer
      - in: path
        name: z2
        required: true
        schema:
          title: Z2
          type: integer
      - in: path
        name: facet
        required: true
        schema:
          $ref: '#/components/schemas/Facet'
      - in: query
        name: poster_res
        required: false
        schema:
          default: 64
          title: Poster Res
          type: integer
      responses:
        '200':
          content:
            image/png: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Hposter
  /poster/{x}.{y}.{z}/{facet}:
    get:
      operationId: poster_poster__x___y___z___facet__get
      parameters:
      - in: path
        name: x
        required: true
        schema:
          title: X
          type: integer
      - in: path
        name: y
        required: true
        schema:
          title: Y
          type: integer
      - in: path
        name: z
        required: true
        schema:
          title: Z
          type: integer
      - in: path
        name: facet
        required: true
        schema:
          $ref: '#/components/schemas/Facet'
      - in: query
        name: poster_res
        required: false
        schema:
          title: Poster Res
          type: integer
      responses:
        '200':
          content:
            image/png: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Poster

