on:
  push:

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:

    # Setup workspace for checks

    - name: Check out repository code
      uses: actions/checkout@v3.2.0
    - name: Setup python 3.11
      uses: actions/setup-python@v4.3.1
      with:
        python-version: '3.11'
    - name: Install code dependency
      run: make deps

    # Run checks and tests

    - name: Checks and tests
      run: make check

    - name: Run mdl for check markdown format
      uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        files: .
        config_file: .markdownlint.yaml
